[package]
name = "calendar_calc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.12.0", features = ["napi4"] }
napi-derive = "2.14.1"

[build-dependencies]
napi-build = "2.0.1"