/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function getVersion(): string
export declare function getFeatures(): Array<string>
export declare function getCpuCount(): number
export declare function calculateDateDifference(startDate: string, endDate: string): string
export declare function calculateDateDifferencesSequential(pairsJson: string): string
export declare function calculateDateDifferencesParallel(pairsJson: string): Promise<string>
